version: 2.1

workflows:
  build-test-and-deploy:
    jobs:
      - test
      - test1:
          requires:
            - test
      - build:
          requires:
            - test1
jobs:
  test:
    docker:
      - image: cimg/gcp:2022.08.1
    steps:
      - checkout
      - run: echo "Do things"
  test1:
    docker:
      - image: cimg/gcp:2022.08.1
    steps:
          - checkout
          - run: mkdir test-reports
          - run:
                name: Download Selenium
                command: curl -O http://selenium-release.storage.googleapis.com/3.>
          - run:
               name: Start Selenium
               command: java -jar selenium-server-standalone-3.5.3.jar -log test-r>
               background: true
  build:
    docker:
      - image: cimg/node:16.13.1-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "running fine"
